    //------------------------------------------------------------------------------
    // <auto-generated>
    //     Этот код создан по шаблону.
    //
    //     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
    //     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
    // </auto-generated>
    //------------------------------------------------------------------------------

    namespace PCAdminApp.Data
    {
        using System;
        using System.Collections.Generic;
    
        public partial class Computer
        {
            [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
            public Computer()
            {
                this.MaintenanceLog = new HashSet<MaintenanceLog>();
                this.Ticket = new HashSet<Ticket>();
            }
    
            public int Id { get; set; }
            public string PCName { get; set; }
            public string IpAddress { get; set; }
            public int ZoneId { get; set; }
            public int StatusId { get; set; }
            public int HardwareProfileId { get; set; }
            public int PeripheralProfileId { get; set; }
            public System.DateTime LastMaintenanceDate { get; set; }
    
            public virtual HardwareProfile HardwareProfile { get; set; }
            public virtual PeripheralProfile PeripheralProfile { get; set; }
            public virtual Status Status { get; set; }
            public virtual Zone Zone { get; set; }
            [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
            public virtual ICollection<MaintenanceLog> MaintenanceLog { get; set; }
            [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
            public virtual ICollection<Ticket> Ticket { get; set; }
        }
    }
