//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCAdminApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceLog
    {
        public int Id { get; set; }
        public int ComputerId { get; set; }
        public int UserId { get; set; }
        public string ActionDescription { get; set; }
        public System.DateTime LogDate { get; set; }
    
        public virtual Computer Computer { get; set; }
        public virtual User User { get; set; }
    }
}
