//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCAdminApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeripheralProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PeripheralProfile()
        {
            this.Computer = new HashSet<Computer>();
        }
    
        public int Id { get; set; }
        public string ProfileName { get; set; }
        public string MouseModel { get; set; }
        public string KeyboardModel { get; set; }
        public string HeadsetModel { get; set; }
        public string MonitorModel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Computer> Computer { get; set; }
    }
}
